<h1>Add article</h1>

<?php
$form = $this->form;
$form->setAttributes(array(
    'action', $this->url(),
    'method' => 'post',
    'class'  => 'form-horizontal'
));
$form->prepare();

echo $this->form()->openTag($form);

// echo $this->formCollection($form); // display form with one line

echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <?php
    echo $this->formLabel($form->get('title')->setLabelAttributes(array('class' => 'control-label')));
    echo $this->formInput($form->get('title')->setAttributes(array('class' => 'form-control', 'placeholder' => 'Title')));
    echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formLabel($form->get('author')->setLabelAttributes(array('class' => 'control-label')));
    echo $this->formSelect($form->get('author')->setAttributes(array('class' => 'form-control')));
    echo $this->formElementErrors($form->get('author'), array('class' => 'help-inline'));
    ?>
</div>
<div class="form-group">
    <?php
    echo $this->formLabel($form->get('content')->setLabelAttributes(array('class' => 'control-label')));
    echo $this->formTextarea($form->get('content')->setAttributes(array('class' => 'form-control', 'placeholder' => 'Content', 'rows' => '4')));
    echo $this->formElementErrors($form->get('content'), array('class' => 'help-inline'));
    ?>
</div>

<input type="submit" value="Add" class="btn btn-default">

<?php echo $this->form()->closeTag();
